CREATE TABLE ARTICLES
(
	ID          VARCHAR(50)   NOT NULL COMMENT '아이디',
	TITLE       VARCHAR(300)  NOT NULL COMMENT '제목',
	CONTENT     TEXT          NOT NULL COMMENT '내용',
	AUTHOR_ID   VARCHAR(50)   NOT NULL COMMENT '작성자',
	AUTHOR_NAME VARCHAR(1000) NOT NULL COMMENT '작성자 이름',
	CREATED_AT  TIMESTAMP     NULL COMMENT '생성일시',
	UPDATED_AT  TIMESTAMP     NULL COMMENT '수정일시',
	PRIMARY KEY (ID)
);

