server:
  port: 0
eureka:
  client:
    service-url:
      default-zone: http://172.21.1.170:8761/eureka
  instance:
    prefer-ip-address: true #서비스간 통신 시 hostname 보다 ip 를 우선 사용 함
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: info,health,refresh

logging:
  level:
    org.springframework.web: debug
