CREATE TABLE ACCOUNTS
(
	ID         VARCHAR(50)  NOT NULL COMMENT '아이디',
	USERNAME   VARCHAR(100) NOT NULL COMMENT '로그인 아이디',
	PASSWORD   VARCHAR(100) NOT NULL COMMENT '비밀번호',
	EMAIL      VARCHAR(100) NOT NULL COMMENT '이메일',
	NAME       VARCHAR(100) NOT NULL COMMENT '이름',
	CREATED_AT TIMESTAMP    NULL COMMENT '생성일시',
	PRIMARY KEY (ID)
);
