INSERT INTO ACCOUNTS
    (ID, NAME)
VALUES
	('TEST-ACCOUNTS-001', '조쉬홍')
;

INSERT INTO ARTICLES
    (ID, TITLE, CONTENT, ACCOUNT_ID, CREATED_AT, UPDATED_AT)
VALUES
	('TEST-ARTICLE-001', '샘플 게시글', '샘플입니다.', 'TEST-ACCOUNTS-001', NOW(), NULL)
;
